INSERT INTO productos (nombre, precio, create_at) VALUES ('Mouse Logitech G203', 550000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Teclado Redragon km-ultra', 430000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Monitor Asus ROG 240hz', 3400000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Laptop Dell XPS 13', 2500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Silla Gamer DXRacer', 1200000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tablet Samsung Galaxy Tab S7', 1500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartphone iPhone 13 Pro', 4500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartwatch Apple Watch Series 7', 1600000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Disco Duro Externo Seagate 2TB', 300000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Memoria RAM Corsair Vengeance 16GB', 350000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tarjeta Gráfica Nvidia RTX 3080', 6800000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Teclado Mecánico Corsair K95', 600000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mouse Inalámbrico Logitech MX Master 3', 450000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara Web Logitech Brio 4K', 800000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Monitor Dell Ultrasharp 27"', 2700000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Parlantes Bose SoundLink', 950000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Router ASUS RT-AX88U', 1100000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Impresora Multifuncional HP LaserJet Pro', 1300000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Consola de Videojuegos PlayStation 5', 3500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara DSLR Canon EOS R5', 9000000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Auriculares Sony WH-1000XM4', 700000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Microondas Samsung 32L', 450000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Televisor LG OLED 65"', 6000000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cafetera Nespresso Vertuo', 350000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Ventilador Xiaomi Mi Smart Standing Fan', 200000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Aspiradora Dyson V11', 1200000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Refrigerador Samsung Twin Cooling Plus', 5000000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tablet Amazon Fire HD 10', 350000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Purificador de Aire Xiaomi Mi Air Purifier 3H', 450000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara de Seguridad Nest Cam IQ', 750000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bicicleta Eléctrica Specialized Turbo Vado', 9500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bicicleta Mountain Bike Trek Marlin 5', 1800000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartphone Samsung Galaxy S21 Ultra', 4000000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tablet Microsoft Surface Pro 7', 2700000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara de Acción GoPro HERO9 Black', 1200000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartwatch Garmin Fenix 6', 2500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cargador Inalámbrico Anker PowerWave', 150000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Audífonos True Wireless Jabra Elite 75t', 400000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Base para Laptop Cooler Master Notepal', 250000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Disco Duro SSD Samsung 970 EVO 1TB', 450000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Router TP-Link Archer AX6000', 950000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Impresora 3D Creality Ender 3', 1500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Consola de Videojuegos Xbox Series X', 3200000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Reproductor de Streaming Roku Ultra', 350000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Proyector BenQ TK850i 4K', 2500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Soundbar Sonos Arc', 1800000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Estación Meteorológica Netatmo', 800000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Freidora de Aire Philips Airfryer XXL', 700000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartphone Google Pixel 6 Pro', 3500000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Laptop Gaming ASUS ROG Strix G17', 4700000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tablet Lenovo Tab P11 Pro', 1100000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara Compacta Sony RX100 VII', 3000000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Auriculares Bluetooth Bose QuietComfort 35 II', 650000, NOW());
